### PR TITLE
Fix: unicode idents, generic inherit. Add scopes

### PR DESCRIPTION
**Pull request by ozra**
Just some small bug fixes / touch ups, plus enable highlighting "secondary" keywords and "end" differently through discriminating scopes.

### CODE REVIEW

**Comment by waj** [comment]
Thanks!

**Comment by pyros2097** [comment]
If you are pushing a new version please push a new tag with semantic version like v0.0.2 This will update the sublime package control. So everyone gets the changes.

**Comment by ozra** [comment]
I've got some more fixes coming up, thought I'd accumulate some fixes while getting some testing miles in different sources before PR'ing.

That tag thing, is it something I'm supposed to do - or the PR accepter? (_Not_ a git ninja... yet)

**Comment by pyros2097** [comment]
You can do this once you think its ready for a new version and want to distribute it to other people.
You can see all the previous tags in github and just increment the the last digit.
You need to do the tag thing the PR will just merge it and sublime package control will automatically upgrade the package, do this when your ready and after you have committed
```sh
git tag v0.0.2
git push --tags
```

**Comment by ozra** [comment]
Cool. But it will be a increment of minor. Because some additional scopes was introduced in the previous PR, enabling more detailed coloring for those who wants it. Eh, unless you only inc patch as long as it's 0.* ?

**Comment by pyros2097** [comment]
Yeah that's fine. I just said this `increment the the last digit.`  as a example. You usually increase patch for small things like bug fixes and minor for some new features and major for api breaking changes thats semantic for you.

**Comment by waj** [comment]
I just tagged v0.0.2. Thanks!

**Comment by ozra** [comment]
@pyros2097 well, semver I know, just git I'm still rudimentary knowledgable about :)
@waj it should be v0.1.0 based on the additional scope features, staying true to semver. But can do that in next PR. :)

**Pull request merged**
